cmake_minimum_required(VERSION ${CMAKE_VERSION})

file(WRITE ${OUTPUT} "/* Autogenerated by bin2c.cmake */\n\n")

file(APPEND ${OUTPUT} "static const char ${IDENT}[] = {\n\t")

file(READ ${INPUT} FILE_CONTENT HEX)
string(REGEX MATCHALL "([0-9a-zA-Z][0-9a-zA-Z])" result ${FILE_CONTENT})
foreach(bin ${result})
    file(APPEND ${OUTPUT} "0x${bin}, ")
endforeach()

file(APPEND ${OUTPUT} "\n};\n")
